// Authored for these short Play films, not read verbatim from their captions.
// Keep one decision per clip. i and j are spoken as pointer names, not code.
import { playFilms } from '../../app/film-catalog.ts';

const scripts = {
  selection: [
    "Okay, we're filling the first position. Start by remembering four, then scan to the right for something smaller. Nothing moves yet.",
    "One is smaller than four. Remember one as our new minimum. We're changing our choice, not swapping the array.",
    "Three doesn't beat one, so keep one in mind and keep scanning.",
    "Five doesn't beat one either. Our minimum stays the same.",
    'Two is smaller than some values here, but not smaller than one. The full scan is finished now.',
    'Now we move. Swap one with four, putting one at the front. That first position is finished.',
    "We're filling the next position. Three beats four, so remember three. The finished one stays put.",
    'Five is larger than three. Keep the same minimum and check the next value.',
    "Two beats three. Update the minimum again. That's why we finish the scan before placing anything.",
    'Swap two into the second position. One and two are now fixed; only the remaining suffix needs work.',
    "For the next position, three is our starting minimum. Five doesn't beat it.",
    "Four doesn't beat three either. We've checked the whole remaining suffix.",
    'Three is already where it belongs. No swap needed; just grow the finished prefix.',
    'One last scan. Four beats five, so four is the value we want next.',
    'Swap four and five. The last remaining value falls into place too.',
    "That's selection sort: scan the whole unfinished part, remember the smallest, then place it once. The finished prefix grows from the left.",
  ],
  insertion: [
    "Start with just four as our sorted prefix. We'll take each new value and give it a place inside that prefix.",
    'Our key is seven. Compare it with four, the neighbor to its left. Four is smaller, so nothing needs to shift.',
    'Seven stays here. Four and seven now form the sorted prefix.',
    'Next key: eight. Compare with seven. Seven is smaller, and everything before it is already sorted.',
    'Eight stays put too. Our sorted prefix is now four, seven, eight.',
    "Now the key is two. Eight is larger, so two can't stay here. Watch the larger values move right.",
    'Eight shifts one position right. The blue two follows the open slot so you can see its possible destination. Next, compare with seven.',
    'Seven is larger than two as well. Shift seven right, and look one position further left, at four.',
    'Four is larger too, so it shifts right. Two has reached the front; there is nothing left to compare.',
    'Insert two at the front. The prefix is now two, four, seven, eight. In code, the key was held separately during those shifts.',
    'Take five as the next key. Eight is larger, so we need to make room again.',
    'Shift eight right. Five follows the open slot, and the next value to check is seven.',
    'Seven shifts right too. Now check four. Four is smaller than five, so this is where we stop.',
    "Insert five after four. We didn't need to revisit two, because the old prefix was already sorted.",
    "That's insertion sort: hold a key, shift larger neighbors right, then insert. Each completed pass grows a sorted prefix by one.",
  ],
  shell: [
    'Think of gap two as two lanes inside one array. The purple lane uses indices zero, two, and four. The other positions sit this insertion out.',
    'Hold zero from index four. Compare it with six at index two, exactly one gap to the left. Zero is smaller, so make room.',
    'Six shifts from index two to four. The blue zero follows the open slot at index two. Next compare with two at index zero, not the neighboring one.',
    "Two also shifts right by the gap. Zero reaches the front of its lane. The odd-indexed values haven't moved at all.",
    "Insert zero. The even lane is zero, two, six; the odd lane is one, three, five. Each lane is ordered, but the whole array isn't sorted yet.",
    'Now shrink the gap to one. All positions share a lane. In this example, only the final five needs to move past six.',
    'Shift six one slot right. Compare five with three next. Three is smaller, so stop here.',
    'Insert five after three. Gap two sorted separate lanes; gap one finished the array. Same insertion idea, different distance.',
  ],
  quick: [
    'Start with three samples: four, nine, and one. The middle value by size is four, our pivot. First, put the samples in order.',
    'Swap four and one. One becomes the smallest sample on the left. Our pivot value is still four.',
    'Swap nine and four. The samples are now one, four, nine. Four sits between the other samples.',
    'Park the pivot near the right end. The left scan stops on seven, too large. The right scan stops on three, too small.',
    'Swap seven and three. They were on the wrong sides of four. The pivot stays parked while we keep scanning.',
    'The next stopped pair is eight and two. Eight belongs to the right of four; two belongs to the left.',
    'Swap them. Two moves left and eight moves right. Now let the scans move toward each other again.',
    "The scan indices have crossed: three is past two. There's no pair left to swap. We can place the pivot now.",
    'Move four into its final position. Smaller values are to its left, larger values to its right. Those sides are partitioned, not necessarily sorted.',
    'The left side has only three values, so this version finishes it with insertion sort. Move two before three. Four stays fixed.',
    'The right side is still large enough to partition. Its samples are seven, six, nine. Their median is seven, the next pivot.',
    'Park seven. Here the local scans cross without finding a pair to exchange. We still need to put the pivot in place.',
    'Place seven between its sides. That leaves the small ranges six, five and eight, nine. Use insertion sort to finish them.',
    "Move five before six; eight and nine are already ordered. That's the pattern: fix a pivot, solve smaller sides, and leave fixed pivots alone.",
  ],
  merge: [
    'Okay, six unsorted values. Rather than sorting everything at once, split the problem into smaller pieces, then bring sorted pieces back together.',
    'Our halves are seven, one, four and six, two, three. Neither half is sorted yet. Keep splitting.',
    "One value on its own is already sorted. That's the stopping point for splitting, and the starting point for merging.",
    'Start with one and four. Their pair is already ordered. Next, merge seven into that sorted pair.',
    'One beats seven, then four beats seven. Take one, four, then the remaining seven. Only the left half changes.',
    'On the right, two and three already make an ordered pair. Now bring six into that pair. The finished left half stays put.',
    "Take two, then three, then six. Both halves are sorted now. Here's where the smaller-front idea really helps.",
    'Only compare the first unused value in each half. Because each half is sorted, nothing behind its front can be smaller. Choose the smaller front.',
    'One beats two. Copy one into the first output slot. Move only the left pointer; the right pointer stays put.',
    "Now it's four versus two. Take two, and move only the right pointer. Four keeps waiting at the left front.",
    'Four versus three. Three is smaller, so copy it next. Advance the right pointer again.',
    'Four versus six. This time four wins. Copy four, and move the left pointer to seven.',
    'Seven versus six. Take six. That uses the last value from the right half.',
    'Only seven remains. Copy it into the final slot. No comparison needed when the other half is empty.',
    "Sorted: one, two, three, four, six, seven. Split into easy pieces, then keep taking the smaller front. That's merge sort.",
  ],
  tim: [
    "Tim sort looks for order that's already there. Here, one, four, seven are ascending before the array drops back to two.",
    'That drop ends the first run. One, four, seven are already sorted, so keep that work instead of starting over.',
    'The second run is two, three, six. Our teaching example uses a minimum run of three, so both runs are long enough. No extension is needed here.',
    "Now merge the runs by comparing their unused fronts. You don't need to search the whole run; its front is its smallest remaining value.",
    'One beats two. Copy one into output and move only the pointer in the first run.',
    'Four versus two. Take two from the second run. Four waits where it is.',
    "Four versus three. Take three, then advance the second run's pointer again.",
    "Four is smaller than six. Copy four, and move the first run's pointer to seven.",
    'Seven versus six. Take six. The second run is now used up.',
    "Copy the remaining seven. With only one run left, we don't need another comparison.",
    'Reuse order, then merge. Short runs would first be extended with insertion sort. Full Tim sort also manages its run stack; this film isolates the basic idea.',
  ],
  counting: [
    "Here's the distinction: six input items, but only four possible integer values, zero through three. Make four count buckets and six output slots, not six buckets.",
    "Read two from the input. Add one to bucket two. We're counting an occurrence; the input value stays where it is.",
    'Read one. Its bucket goes from zero to one. Each bucket is named for a value, not an input position.',
    'Another two. Bucket two goes from one to two. Same value, same bucket.',
    'Read zero. Bucket zero becomes one. Zero needs its own bucket too.',
    "Read three. Add one to bucket three. We still haven't placed anything in the output.",
    "One appears again. Its bucket becomes two. That's all six input values counted.",
    "We have one zero, two ones, two twos, and one three. These numbers are frequencies, not output indices. Next we'll turn them into positions.",
    'There are two ones and one smaller value. Three values are at most one, so the ones belong at output indices one and two.',
    'Add the two twos to those three earlier values. Five values are at most two. The twos belong at indices three and four.',
    'Add the one three. All six values are at most three, so three belongs at the last output index, five.',
    "The buckets now hold cumulative totals. Subtract one to get a value's rightmost free output slot. The zero bucket already gave us its total of one.",
    'Read from the right: one. Its total is three, so subtract one and copy it to index two. Its bucket becomes two, ready for the earlier one.',
    'Next is three. Six minus one gives index five. Copy three there and update its bucket.',
    "Zero's bucket says one. One minus one gives index zero, the first slot. Copy zero there.",
    'This two uses five minus one: index four. Copy it there. The next two will take the earlier slot in the same range.',
    'The earlier one now uses two minus one: index one. It lands before the later one, preserving their original order.',
    'The earlier two uses four minus one: index three. Equal values keep their input order because we read right to left and fill their ranges from the right.',
    'Done: zero, one, one, two, two, three. Count occurrences, turn counts into ranges, then fill those ranges. Input length and value range are different sizes.',
  ],
};

export const narrationSource = (scene) =>
  JSON.stringify({
    title: scene.title,
    caption: scene.caption,
    operation: scene.operation,
    tokens: scene.tokens,
    merge: scene.merge,
    counting: scene.counting,
    held: scene.held,
    gap: scene.gap,
    group: scene.group,
  });

export const sortingNarration = Object.fromEntries(
  Object.entries(scripts).map(([id, texts]) => {
    const frames = playFilms[id].frames;
    if (texts.length !== frames.length) throw new Error(`${id}: narration must match every Play scene.`);
    return [id, texts.map((text, index) => ({ text, source: narrationSource(frames[index]) }))];
  }),
);
