// Model: algorithm facts and learning cues stay separate from the Svelte view.
export const algorithms = [
  {
    id: 'quick',
    name: 'Quick Sort',
    difficulty: 5,
    cue: 'Choose a pivot → partition → recurse on each side.',
    divide: 'Yes',
    lower: 'Ω(n log n), balanced partitions',
    upper: 'O(n²)',
    extra: 'Insertion sort handles small ranges in this walkthrough.',
    walkthrough: 'quick_sort_partition_walkthrough.html',
    python: 'quick_sort.py',
    simplePython: 'quick_sort_simple.py',
    javascript: 'quick_sort.js',
    typescript: 'quick_sort.ts',
  },
  {
    id: 'merge',
    name: 'Merge Sort',
    difficulty: 3,
    cue: 'Split to singles → compare the fronts → merge.',
    divide: 'Yes',
    lower: 'Ω(n log n)',
    upper: 'O(n log n)',
    extra: 'Θ(n) auxiliary space.',
    walkthrough: 'merge_sort_walkthrough.html',
    python: 'merge_sort.py',
    simplePython: 'merge_sort_simple.py',
    javascript: 'merge_sort.js',
    typescript: 'merge_sort.ts',
  },
  {
    id: 'tim',
    name: 'Tim Sort',
    difficulty: 7,
    cue: 'Find ordered runs → extend short runs → merge.',
    divide: 'Yes, while merging runs',
    lower: 'Ω(n), when the data is already one ordered run',
    upper: 'O(n log n)',
    extra: 'Adaptive hybrid; Python file is an educational version.',
    walkthrough: 'tim_sort_walkthrough.html',
    python: 'tim_sort.py',
    simplePython: 'tim_sort_simple.py',
    javascript: 'tim_sort.js',
    typescript: 'tim_sort.ts',
  },
  {
    id: 'insertion',
    name: 'Insertion Sort',
    difficulty: 2,
    cue: 'Grow a sorted prefix → shift larger values → insert the key.',
    divide: 'No',
    lower: 'Ω(n), already ordered input',
    upper: 'O(n²)',
    extra: 'Θ(1) auxiliary space.',
    walkthrough: 'insertion_sort_walkthrough.html',
    python: 'insertion_sort.py',
    simplePython: 'insertion_sort_simple.py',
    javascript: 'insertion_sort.js',
    typescript: 'insertion_sort.ts',
  },
  {
    id: 'selection',
    name: 'Selection Sort',
    difficulty: 1,
    cue: 'Scan the unsorted suffix → choose its minimum → swap.',
    divide: 'No',
    lower: 'Ω(n²) comparisons',
    upper: 'O(n²)',
    extra: 'At most n−1 swaps.',
    walkthrough: 'selection_sort_walkthrough.html',
    python: 'selection_sort.py',
    simplePython: 'selection_sort_simple.py',
    javascript: 'selection_sort.js',
    typescript: 'selection_sort.ts',
  },
  {
    id: 'shell',
    name: 'Shell Sort',
    difficulty: 6,
    cue: 'Compare within gap groups → shrink the gap → finish at gap one.',
    divide: 'No',
    lower: 'Θ(n log n), already ordered input with halving gaps',
    upper: 'O(n²), halving-gap sequence',
    extra: 'Runtime bounds depend on the gap sequence.',
    walkthrough: 'shell_sort_walkthrough.html',
    python: 'shell_sort.py',
    simplePython: 'shell_sort_simple.py',
    javascript: 'shell_sort.js',
    typescript: 'shell_sort.ts',
  },
  {
    id: 'counting',
    name: 'Counting Sort',
    difficulty: 4,
    cue: 'Count values → cumulative positions → place right-to-left.',
    divide: 'No',
    lower: 'Θ(n + k)',
    upper: 'O(n + k)',
    extra: 'k is the integer range width; supports negative values.',
    walkthrough: 'counting_sort_walkthrough.html',
    python: 'counting_sort.py',
    simplePython: 'counting_sort_simple.py',
    javascript: 'counting_sort.js',
    typescript: 'counting_sort.ts',
  },
];

// View-model projection: search never mutates the algorithm records.
export function visibleAlgorithms(query) {
  const term = query.trim().toLowerCase();
  if (!term) return algorithms;
  return algorithms.filter((algorithm) =>
    [algorithm.name, algorithm.cue, algorithm.divide, algorithm.lower, algorithm.upper, algorithm.extra]
      .join(' ')
      .toLowerCase()
      .includes(term),
  );
}

